GET http://localhost:3000/subscribers


###

GET http://localhost:3000/subscribers/6350d6e92cf6fafd180a9696

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Emily",
    "subscribedToChannel": "channel"
}

###
DELETE http://localhost:3000/subscribers/63544ad37ab75cc5f800d8da


###

PATCH http://localhost:3000/subscribers/6350d6e92cf6fafd180a9696
Content-Type: application/json

{
    "name": "New Name"
}
